import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Relogio from "@/components/Relogio/Relogio";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}
        min-h-screen
        flex flex-col
        justify-center
        items-center`}
      >

        <header>
          <h1> React e Next.js </h1>
          <nav className="flex gap-4">
            <Link href="/">Home</Link>
            <Link href="/rota">Route</Link>
            <Link href="/caracteristicas">Caracteristicas</Link>
            <Link href="/sobre">Sobre</Link>
            <Link href="/tecnologias">Tecnologias</Link>
            <Link href="/projetos">Projetos</Link>
            <Link href="/contador">Contador</Link>
            <Link href="/input">Input</Link>
            <Link href="/produtos">Produtos</Link>
            <Link href="/categorias">Categorias</Link>
          </nav>
        </header>
        <main className="bg-pink-300 w-[70vw] min-h-[40vw] p-3">
          {children}
        </main>
        <footer><Relogio /></footer>
      </body>
    </html>
  );
}
